version: 2.1.668.{build}
init:
  - git config --global core.autocrlf input
clone_depth: 10
branches:
  except:
  - gh-pages
image: Visual Studio 2017
environment:
  nuget_version: 2.0.7.668
skip_tags: true
platform: Any CPU
configuration: Release
dotnet_csproj:
  patch: true
  file: coreSrc\Directory.build.props
  version: '$(nuget_version)'
  package_version: '$(nuget_version)'
  assembly_version: '$(nuget_version)'
  file_version: '$(nuget_version)'
  informational_version: '$(APPVEYOR_REPO_COMMIT)'
before_build:
 - cmd: msbuild ProtoBuf.Data.Core.sln /t:restore
build:
  project: ProtoBuf.Data.Core.sln
  verbosity: minimal
# after_build:
# - msbuild  ProtoBuf.Data.Core.sln /t:pack
test_script:
- cmd: dotnet test coreSrc\ProtoBuf.Data.Core.Tests\ProtoBuf.Data.Core.Tests.csproj --configuration Release --no-build --filter "TestCategory!=Integration"
artifacts:
- path: '*.nupkg'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true