version: 2.1.668.{build}
init:
  - git config --global core.autocrlf input
clone_depth: 10
branches:
  except:
  - gh-pages
image: Visual Studio 2017
environment:
  nuget_version: 2.0.7.668
skip_tags: true
configuration: Release
dotnet_csproj:
  patch: true
  file: coreSrc\Directory.build.props
  version: '$(nuget_version)'
  package_version: '$(nuget_version)'
  assembly_version: '$(nuget_version)'
  file_version: '$(nuget_version)'
  informational_version: '$(APPVEYOR_REPO_COMMIT)'
before_build:
 - cmd: msbuild ProtoBuf.Data.Core.sln /t:restore /clp:Summary;Verbosity=minimal
build_script:
 - cmd: msbuild ProtoBuf.Data.Core.sln /t:build /p:SourceLinkCreate=true /p:SourceLinkTest=true /clp:Summary;Verbosity=minimal
after_build:
 - cmd: msbuild ProtoBuf.Data.Core.sln /t:pack /clp:Summary;Verbosity=minimal
test_script:
 - cmd: dotnet test coreSrc\ProtoBuf.Data.Core.Tests\ProtoBuf.Data.Core.Tests.csproj --no-build --filter "TestCategory!=Integration" /logger:Appveyor
artifacts:
 - path: '**\*.nupkg'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true