//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyProduct("Protocol Buffers DataReader extensions for .NET")]
[assembly: AssemblyCopyright("Copyright © Richard Dingwall 2012")]
[assembly: AssemblyVersion("2.0.4.601")]
[assembly: AssemblyFileVersion("2.0.4.601")]
[assembly: AssemblyInformationalVersion("HEAD")]


